version: "3.9"

services:

  postgres:
    container_name: postgresql
    image: postgres:15
    command: ["postgres", "-c", "max_connections=1000"]
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - supplycrew-net

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "4000:80"
    env_file:
      - ./backend/.env
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - supplycrew-net

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    networks:
      - supplycrew-net
    depends_on:
      - postgres
    restart: always

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
    networks:
      - supplycrew-net
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data:
  pgadmin_data:

networks:
  supplycrew-net:
    driver: bridge